spring:
  application:
    name: helpdesk
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    br.com.silviofrancoms: DEBUG
    root: warn
#    root: warn // esse aqui serve para logar no root só niveis warn ou error
# Logs level Trace > Debug > Info > Warn > Error // por padrao o projeto começa com info